version: '3'

volumes:
  foodgram_postgre:
  foodgram_static:
  foodgram_media:

services:
  db:
    image: postgres:latest
    env_file: .env
    volumes:
      - foodgram_postgre:/var/lib/postgresql/data
  backend:
    image: zionweeds/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - foodgram_media:/foodgram_app/media/
      - foodgram_static:/backend_static
  frontend:
    env_file: .env
    image: zionweeds/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - foodgram_static:/frontend_static
  nginx:
    depends_on:
      - db
      - backend
    volumes:
       - foodgram_static:/staticfiles
       - foodgram_media:/foodgram_app/media/
    image: zionweeds/foodgram_nginx
    ports:
      - 8000:80
